name: Add assets to release

on:
  release:
    types:
      - published

jobs:
  build:
    name: Build packages
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-22.04
            TARGET: linux
            CMD_BUILD: >
                poetry run pyinstaller --clean -F --hidden-import audible_cli -n audible -c pyi_entrypoint.py &&
                cd dist/ &&
                zip -r9 audible_linux_ubuntu_22_04 audible
            OUT_FILE_NAME: audible_linux_ubuntu_22_04.zip
            ASSET_MIME: application/zip  # application/octet-stream

          - os: ubuntu-20.04
            TARGET: linux
            CMD_BUILD: >
                poetry run pyinstaller --clean -F --hidden-import audible_cli -n audible -c pyi_entrypoint.py &&
                cd dist/ &&
                zip -r9 audible_linux_ubuntu_20_04 audible
            OUT_FILE_NAME: audible_linux_ubuntu_20_04.zip
            ASSET_MIME: application/zip  # application/octet-stream

          - os: macos-latest
            TARGET: macos
            CMD_BUILD: >
                poetry run pyinstaller --clean -F --hidden-import audible_cli -n audible -c pyi_entrypoint.py &&
                cd dist/ &&
                zip -r9 audible_mac audible
            OUT_FILE_NAME: audible_mac.zip
            ASSET_MIME: application/zip

          - os: macos-latest
            TARGET: macos
            CMD_BUILD: >
                poetry run pyinstaller --clean -D --hidden-import audible_cli -n audible -c pyi_entrypoint.py &&
                cd dist/ &&
                zip -r9 audible_mac_dir audible
            OUT_FILE_NAME: audible_mac_dir.zip
            ASSET_MIME: application/zip

          - os: windows-latest
            TARGET: windows
            CMD_BUILD: >
                poetry run pyinstaller --clean -D --hidden-import audible_cli -n audible -c pyi_entrypoint.py &&
                cd dist/ &&
                powershell Compress-Archive audible audible_win_dir.zip
            OUT_FILE_NAME: audible_win_dir.zip
            ASSET_MIME: application/zip

          - os: windows-latest
            TARGET: windows
            CMD_BUILD: >
                poetry run pyinstaller --clean -F --hidden-import audible_cli -n audible -c pyi_entrypoint.py &&
                cd dist/ &&
                powershell Compress-Archive audible.exe audible_win.zip
            OUT_FILE_NAME: audible_win.zip
            ASSET_MIME: application/zip

    steps:
      - uses: actions/checkout@v3
 
      - name: Add assets for published releases
        uses: ./.github/workflows/add-assets-workflow-call.yml
        with:
          upload_url: ${{ github.event.release.upload_url }}
